"""initsial migration

Revision ID: 57ea9de8807a
Revises:
Create Date: 2025-01-06 21:44:33.874193

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57ea9de8807a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "industry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_industry_id"), "industry", ["id"], unique=True)
    op.create_index(
        op.f("ix_industry_name"), "industry", ["name"], unique=True
    )
    op.create_index(op.f("ix_industry_uid"), "industry", ["uid"], unique=True)
    op.create_table(
        "phone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_index(op.f("ix_phone_id"), "phone", ["id"], unique=True)
    op.create_index(op.f("ix_phone_uid"), "phone", ["uid"], unique=True)
    op.create_table(
        "organization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("industry_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["industry_id"], ["industry.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_id"), "organization", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_organization_uid"), "organization", ["uid"], unique=True
    )
    op.create_table(
        "specialization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("industry_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["industry_id"], ["industry.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_specialization_id"), "specialization", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_specialization_name"), "specialization", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_specialization_uid"), "specialization", ["uid"], unique=True
    )
    op.create_table(
        "address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("street", sa.String(), nullable=False),
        sa.Column("home_number", sa.Integer(), nullable=False),
        sa.Column("room_number", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Numeric(), nullable=False),
        sa.Column("longitude", sa.Numeric(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_address_id"), "address", ["id"], unique=True)
    op.create_index(op.f("ix_address_uid"), "address", ["uid"], unique=True)
    op.create_table(
        "organization_specializations",
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("specialization_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"], ["specialization.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("organization_id", "specialization_id"),
        sa.UniqueConstraint(
            "organization_id",
            "specialization_id",
            name="uix_organization_specializations",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_specializations")
    op.drop_index(op.f("ix_address_uid"), table_name="address")
    op.drop_index(op.f("ix_address_id"), table_name="address")
    op.drop_table("address")
    op.drop_index(op.f("ix_specialization_uid"), table_name="specialization")
    op.drop_index(op.f("ix_specialization_name"), table_name="specialization")
    op.drop_index(op.f("ix_specialization_id"), table_name="specialization")
    op.drop_table("specialization")
    op.drop_index(op.f("ix_organization_uid"), table_name="organization")
    op.drop_index(op.f("ix_organization_id"), table_name="organization")
    op.drop_table("organization")
    op.drop_index(op.f("ix_phone_uid"), table_name="phone")
    op.drop_index(op.f("ix_phone_id"), table_name="phone")
    op.drop_table("phone")
    op.drop_index(op.f("ix_industry_uid"), table_name="industry")
    op.drop_index(op.f("ix_industry_name"), table_name="industry")
    op.drop_index(op.f("ix_industry_id"), table_name="industry")
    op.drop_table("industry")
    # ### end Alembic commands ###
